global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # alertmanager is not set up in this basic config

rule_files:
  # rules are not set up in this basic config

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'signal_service'
    static_configs:
      - targets: ['signal:9090']

  - job_name: 'risk_service'
    static_configs:
      - targets: ['risk:9092']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
