# MLbotnew 手数料設定
# バックテスト実行時に使用される手数料・スリッページ設定

# 取引手数料設定 (%)
fees:
  default: 0.00055  # デフォルト: 0.055%
  bybit: 0.00055    # Bybit: 0.055%
  binance: 0.0004   # Binance: 0.04%

# スリッページ設定 (%)
slippage:
  default: 0.0001   # デフォルト: 0.01%
  backtest: 0.0001  # バックテスト用: 0.01%
  
# 取引オプション
trading_options:
  # バックテスト実行オプション
  backtest:
    upon_op: "Next"  # 注文実行タイミング（Next: 次の足で約定）
    size_pct: 1.0    # ポジションサイズ（資金に対する割合）
    
  # ライブ取引オプション
  live:
    limit_distance: 0.0005  # 指値注文の距離（価格の0.05%）
    timeout_seconds: 60     # 注文タイムアウト（秒）
