name: test-bt-docker
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
          
      - name: Run unit tests
        run: pytest -q

  quick_bt:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create directories
        run: |
          mkdir -p data/raw/15m data/raw/2h data/raw/1d
          mkdir -p data/features/15m data/features/2h data/features/1d
          mkdir -p reports/15m reports/2h reports/1d
          
      - name: Run quick backtest (15m)
        run: python scripts/run_backtest.py --interval 15m --quick
        
      - name: Validate backtest results
        run: python scripts/validate_stats.py
        
      - name: Upload stats
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: reports/*/stats.json
          
      - name: Upload backtest report
        uses: actions/upload-artifact@v4
        with:
          name: bt_reports
          path: reports/*/bt_with_price.html

  docker:
    needs: quick_bt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: mlbotnew:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
